DB:
  DATABASE_ENGINE: xxxxxxxxxx
  DATABASE_USER: xxxxxxxxxxx
  DATABASE_PASS: xxxxxxxxx
  DATABASE_NAME: xxxxxxxxx
  DATABASE_HOST: xxxxxxxxxxx
  DATABASE_PORT: xxxxxxxxx
SECRET_KEY: xxxxxxxxxxxx
GEOPOSITION_GOOGLE_MAPS_API_KEY: YOUR_API_KEY
EMAIL_HOST: xxxxxx
EMAIL_HOST_USER: xxxxx
EMAIL_HOST_PASSWORD: xxxxxxxxx
EMAIL_PORT: xxx
EMAIL_USE_TLS: xxx