# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0033_auto_20170323_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Phone')),
                ('fax', models.CharField(blank=True, max_length=255, verbose_name='Fax')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='Email')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook Page')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter Page')),
                ('googleplus', models.URLField(blank=True, verbose_name='Google+ Page')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn Page')),
                ('city', models.CharField(blank=True, max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(blank=True, max_length=63)),
            ],
            options={
                'verbose_name': 'Contact',
            },
            bases=('wagtailcore.page',),
        ),
    ]
