# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 05:39
from __future__ import unicode_literals

import advertising.models
import advertising.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_advertising', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('timeout', models.PositiveIntegerField(default=0, help_text=b'The input value is in seconds')),
            ],
            options={
                'ordering': ['id_advertising'],
                'verbose_name': 'Advertising',
                'verbose_name_plural': 'Advertising',
            },
        ),
        migrations.CreateModel(
            name='ImageAdvertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('url', models.URLField(max_length=450)),
                ('photo', models.FileField(upload_to=advertising.models.generate_path, validators=[advertising.validators.valid_extension], verbose_name=b'Photo')),
                ('advertising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='advertising.Advertising')),
            ],
        ),
    ]
