# Generated by Junie to switch ImageAdvertising.advertising to ParentalKey for Wagtail inline editing
from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0003_alter_advertising_id_alter_imageadvertising_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageadvertising',
            name='advertising',
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='images',
                to='advertising.advertising',
            ),
        ),
    ]
