# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Event Category', 'verbose_name_plural': 'Event Categories'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Events Tags', 'verbose_name_plural': 'Events Tags'},
        ),
    ]
