# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
    ]
