# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('membership_fr', wagtail.wagtailcore.fields.RichTextField(default='', verbose_name="Conditions d'admission FR")),
                ('membership_en', wagtail.wagtailcore.fields.RichTextField(default='', verbose_name="Conditions d'admission EN")),
                ('members', wagtail.wagtailcore.fields.StreamField([(b'member', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'member_name', wagtail.wagtailcore.blocks.TextBlock(label=b'Nom')), (b'deputy_name', wagtail.wagtailcore.blocks.TextBlock(label=b'Representant')), (b'country', wagtail.wagtailcore.blocks.TextBlock(label=b'Pays')), (b'activity_fr', wagtail.wagtailcore.blocks.TextBlock(label=b'Activite FR')), (b'activity_en', wagtail.wagtailcore.blocks.TextBlock(label=b'Activite EN')), (b'contact', wagtail.wagtailcore.blocks.TextBlock(label=b'Contact', required=False))], icon=b'user', label=b'Membre', required=False))], verbose_name='Membres')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document')),
            ],
            options={
                'verbose_name': 'Member Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='members',
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='officers',
            field=wagtail.wagtailcore.fields.StreamField([(b'office', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'member_name', wagtail.wagtailcore.blocks.TextBlock(label=b'Nom')), (b'deputy_name', wagtail.wagtailcore.blocks.TextBlock(label=b'Representant')), (b'country', wagtail.wagtailcore.blocks.TextBlock(label=b'Pays')), (b'activity_fr', wagtail.wagtailcore.blocks.TextBlock(label=b'Activite FR')), (b'activity_en', wagtail.wagtailcore.blocks.TextBlock(label=b'Activite EN')), (b'contact', wagtail.wagtailcore.blocks.TextBlock(label=b'Contact', required=False)), (b'position_fr', wagtail.wagtailcore.blocks.TextBlock(label=b'Poste FR', required=False)), (b'position_en', wagtail.wagtailcore.blocks.TextBlock(label=b'Poste EN', required=False)), (b'code', wagtail.wagtailcore.blocks.TextBlock(label=b'Code')), (b'code_parent', wagtail.wagtailcore.blocks.TextBlock(label=b'Code Parent'))], icon=b'user', label=b'Membre', required=False))], verbose_name='Bureau'),
        ),
    ]
