# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 16:28
from __future__ import unicode_literals

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='countries',
            field=wagtail.fields.StreamField([(b'countries', wagtail.blocks.StructBlock([(b'flag', wagtail.images.blocks.ImageChooserBlock(label=b'Drapeau')), (b'name', wagtail.blocks.TextBlock(label=b'Nom'))], label=b'Pays Membre', required=False))], blank=True, verbose_name='Pays'),
        ),
    ]
