# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0002_aboutpage_countries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpage',
            options={'verbose_name': 'Product Page'},
        ),
        migrations.AddField(
            model_name='productpage',
            name='excerpt_en',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, default='', help_text='Entry excerpt to be displayed on entries list. If this field is not filled, a truncate version of body text will be used.', verbose_name='excerpt_en'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='excerpt_fr',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, default='', help_text='Entry excerpt to be displayed on entries list. If this field is not filled, a truncate version of body text will be used.', verbose_name='excerpt_fr'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header image'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='products',
            field=wagtail.wagtailcore.fields.StreamField([(b'products', wagtail.wagtailcore.blocks.StructBlock([(b'desc_fr', wagtail.wagtailcore.blocks.RichTextBlock(blank=False, default=b'', verbose_name=b"Description de l'edition FR")), (b'desc_en', wagtail.wagtailcore.blocks.RichTextBlock(blank=False, default=b'', verbose_name=b"Description de l'edition EN")), (b'file_fr', wagtail.wagtaildocs.blocks.DocumentChooserBlock(blank=True, verbose_name=b'Document Version FR')), (b'file_en', wagtail.wagtaildocs.blocks.DocumentChooserBlock(blank=True, verbose_name=b'Document Version FR'))], blank=True, label=b'Produit'))], blank=True),
        ),
    ]
