# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('home', '0002_auto_20170309_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('company_desc_fr', wagtail.wagtailcore.fields.RichTextField(default='', verbose_name="Description de l'association FR")),
                ('company_desc_en', wagtail.wagtailcore.fields.RichTextField(default='', verbose_name="Description de l'association EN")),
                ('members', wagtail.wagtailcore.fields.StreamField([(b'member', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'Member_name', wagtail.wagtailcore.blocks.TextBlock(label='Nom')), (b'deputy_name', wagtail.wagtailcore.blocks.TextBlock(label='Representant')), (b'country', wagtail.wagtailcore.blocks.TextBlock(label='Pays')), (b'activity_fr', wagtail.wagtailcore.blocks.TextBlock(label='Activite FR')), (b'activity_en', wagtail.wagtailcore.blocks.TextBlock(label='Activite EN')), (b'position_fr', wagtail.wagtailcore.blocks.TextBlock(label='Poste FR', required=False)), (b'position_en', wagtail.wagtailcore.blocks.TextBlock(label='Poste EN', required=False)), (b'position_description_fr', wagtail.wagtailcore.blocks.TextBlock(label='Description du Membre FR', required=False)), (b'position_description_en', wagtail.wagtailcore.blocks.TextBlock(label='Description du Membre EN', required=False))], icon='user', label='Membre', required=False))], verbose_name='Membres')),
                ('officers', wagtail.wagtailcore.fields.StreamField([(b'office', wagtail.wagtailcore.blocks.StructBlock([(b'member', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'Member_name', wagtail.wagtailcore.blocks.TextBlock(label='Nom')), (b'deputy_name', wagtail.wagtailcore.blocks.TextBlock(label='Representant')), (b'country', wagtail.wagtailcore.blocks.TextBlock(label='Pays')), (b'activity_fr', wagtail.wagtailcore.blocks.TextBlock(label='Activite FR')), (b'activity_en', wagtail.wagtailcore.blocks.TextBlock(label='Activite EN')), (b'position_fr', wagtail.wagtailcore.blocks.TextBlock(label='Poste FR', required=False)), (b'position_en', wagtail.wagtailcore.blocks.TextBlock(label='Poste EN', required=False)), (b'position_description_fr', wagtail.wagtailcore.blocks.TextBlock(label='Description du Membre FR', required=False)), (b'position_description_en', wagtail.wagtailcore.blocks.TextBlock(label='Description du Membre EN', required=False))], icon='user', label='Membre')), (b'code', wagtail.wagtailcore.blocks.TextBlock(label='Code')), (b'code_parent', wagtail.wagtailcore.blocks.TextBlock(label='Code Parent'))], icon='user', label='Membre', required=False))], verbose_name='Bureau')),
            ],
            options={
                'verbose_name': 'About Us Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
