# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='members',
        ),
    ]
