# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-03-15 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0005_auto_20170406_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header image'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='partners',
            field=wagtail.fields.StreamField((('partners', wagtail.blocks.StructBlock((('name', wagtail.blocks.TextBlock(label='Nom')), ('logo', wagtail.images.blocks.ImageChooserBlock(label='logo')), ('website', wagtail.blocks.TextBlock(label='website', required=False))), label='Partners', required=False)),), blank=True, verbose_name='Partners'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='objectives',
            field=wagtail.fields.StreamField((('objectives', wagtail.blocks.StructBlock((('title_fr', wagtail.blocks.TextBlock(label='Titre_fr')), ('title_en', wagtail.blocks.TextBlock(label='Titre_en')), ('description_fr', wagtail.blocks.TextBlock(label='description_fr')), ('description_en', wagtail.blocks.TextBlock(label='description_en'))), label='Objectifs', required=False)),), blank=True, verbose_name='Objectifs'),
        ),
        migrations.AlterField(
            model_name='memberpage',
            name='members',
            field=wagtail.fields.StreamField((('member', wagtail.blocks.StructBlock((('member_name', wagtail.blocks.TextBlock(label='Nom')), ('country', wagtail.blocks.TextBlock(label='Pays')), ('activity_fr', wagtail.blocks.TextBlock(label='Activite FR')), ('activity_en', wagtail.blocks.TextBlock(label='Activite EN'))), icon='user', label='Membre', required=False)),), blank=True, verbose_name='Membres'),
        ),
        migrations.AlterField(
            model_name='memberpage',
            name='officers',
            field=wagtail.fields.StreamField((('office', wagtail.blocks.StructBlock((('member_name', wagtail.blocks.TextBlock(label='Nom')), ('country', wagtail.blocks.TextBlock(label='Pays')), ('activity_fr', wagtail.blocks.TextBlock(label='Activite FR')), ('activity_en', wagtail.blocks.TextBlock(label='Activite EN')), ('deputy_name', wagtail.blocks.TextBlock(label='Representant')), ('contact', wagtail.blocks.TextBlock(label='Contact', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('position_fr', wagtail.blocks.TextBlock(label='Poste FR', required=False)), ('position_en', wagtail.blocks.TextBlock(label='Poste EN', required=False)), ('biography_fr', wagtail.blocks.RichTextBlock(label='Biography FR', required=False)), ('biography_en', wagtail.blocks.RichTextBlock(label='Biography EN', required=False))), icon='user', label='Membre', required=False)),), blank=True, verbose_name='Bureau'),
        ),
    ]
