# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-03-16 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200315_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='header_image',
            field=models.ForeignKey(blank=True, default=django.db.models.deletion.SET_NULL, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header image'),
        ),
    ]
