# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-03-16 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200316_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='header_image',
            new_name='page_image',
        ),
    ]
