# Generated by Django 4.1.5 on 2023-06-25 01:53

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_aboutpage_page_image_alter_aboutpage_page_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpage',
            name='executive_officers',
            field=wagtail.fields.StreamField([('office', wagtail.blocks.StructBlock([('member_name', wagtail.blocks.TextBlock(label='Nom')), ('country', wagtail.blocks.TextBlock(label='Pays')), ('activity_fr', wagtail.blocks.TextBlock(label='Activite FR')), ('activity_en', wagtail.blocks.TextBlock(label='Activite EN')), ('deputy_name', wagtail.blocks.TextBlock(label='Representant')), ('contact', wagtail.blocks.TextBlock(label='Contact', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('position_fr', wagtail.blocks.TextBlock(label='Poste FR', required=False)), ('position_en', wagtail.blocks.TextBlock(label='Poste EN', required=False)), ('biography_fr', wagtail.blocks.RichTextBlock(label='Biography FR', required=False)), ('biography_en', wagtail.blocks.RichTextBlock(label='Biography EN', required=False))], icon='user', label='Membre', required=False))], blank=True, use_json_field=None, verbose_name='Executive Officers'),
        ),
        migrations.AlterField(
            model_name='memberpage',
            name='officers',
            field=wagtail.fields.StreamField([('office', wagtail.blocks.StructBlock([('member_name', wagtail.blocks.TextBlock(label='Nom')), ('country', wagtail.blocks.TextBlock(label='Pays')), ('activity_fr', wagtail.blocks.TextBlock(label='Activite FR')), ('activity_en', wagtail.blocks.TextBlock(label='Activite EN')), ('deputy_name', wagtail.blocks.TextBlock(label='Representant')), ('contact', wagtail.blocks.TextBlock(label='Contact', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('position_fr', wagtail.blocks.TextBlock(label='Poste FR', required=False)), ('position_en', wagtail.blocks.TextBlock(label='Poste EN', required=False)), ('biography_fr', wagtail.blocks.RichTextBlock(label='Biography FR', required=False)), ('biography_en', wagtail.blocks.RichTextBlock(label='Biography EN', required=False))], icon='user', label='Membre', required=False))], blank=True, use_json_field=None, verbose_name='Officers'),
        ),
    ]
