# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 01:08
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('puput', '0003_add_short_feed_description_to_blog_page'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogpage',
            managers=[
                ('extra', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='entrypage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='entrypage',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='entrypage',
            name='body_en',
            field=wagtail.wagtailcore.fields.RichTextField(default=b'', verbose_name='body_en'),
        ),
        migrations.AddField(
            model_name='entrypage',
            name='body_fr',
            field=wagtail.wagtailcore.fields.RichTextField(default=b'', verbose_name='body_fr'),
        ),
        migrations.AddField(
            model_name='entrypage',
            name='excerpt_en',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, default=b'', help_text='Entry excerpt to be displayed on entries list. If this field is not filled, a truncate version of body text will be used.', verbose_name='excerpt_en'),
        ),
        migrations.AddField(
            model_name='entrypage',
            name='excerpt_fr',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, default=b'', help_text='Entry excerpt to be displayed on entries list. If this field is not filled, a truncate version of body text will be used.', verbose_name='excerpt_fr'),
        ),
    ]
